sudo: required

language: go

services:
  - docker

go:
  - 1.8.3
  - master
  - tip

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - go version | grep -q go1.8.3 && make push && make push-latest
